[Inu] Step3 - 설계 및 이벤트
codesquad-members-2022/fe-shopping pull request #71
Opened 2022-03-23 04:36 UTC by devInu33

# fe-shopping

- [x] 검색창 관련 모듈 개발
- [x] 프로토타입 / 클래스 혼용
- [X] SCSS 및 마크업
- [X] 자동 캐러셀 이벤트
- [] 카테고리 드롭다운 애니메이션
- [] 검색창 방향키 탐색기능

### 설계

모든 웹페이지를 컴포넌트화된 뷰로써 렌더링하고, 각 뷰는 내부에 템플릿을 가집니다. 

- 뷰는 생성되면서 initState로 각각 자신의 상태를 지정하고, 뷰에 존재하는 부모-자식 관계를 위해서 child와 parent라는 필드를 두어 다른 뷰를 가리키게 했습니다.
- 같은 부모를 가리키는 뷰는 next 포인터로 연결되어 형제 노드가 됩니다.
- 외부에서 전역 상태를 관리할 Store 인스턴스를 생성하면서, 가장 상위 App 노드를 자신의 #head 노드로 지정합니다. 노드 순회를 위해 visitor 클래스를 따로 분리하였습니다. 이 클래스를 생성시에 주입받아서
head 노드부터 연결된 모든 컴포넌트 노드들을 순회하면서 각각의 상태를 전역 map에 세팅합니다.
- 전역 상태는 WeakMap을 사용해서 뷰 컴포넌트 개별적으로 상태를 분산해서 가질 수 있게 하였습니다. 처음에는 전역 객체를 사용했으나, 서로 다른 컴포넌트 간에 상태를 침범하는 경우가 일어나서 변경하였습니다다. WeakMap을 사용한 이유는 참조를 gc 해준다고 하여 기능을 사용해보고 싶어서 사용하였습니다.

### 렌더링

모든 렌더링은 각 컴포넌트에서 setState을 통해서만 일어납니다. setState이 일어난 컴포넌트만 렌더링 여부를 알리는 #willRender 플래그가 true로 바뀌고, store에서는
자신의 #head 컴포넌트에 render 명령을 내리면 연결된 모든 자식과 형제 노드의 render를 전부 순회하면서 실행하는데, 이 때 마찬가지로 과거 setState가 일어나서 #willRender가 true인 컴포넌트만 렌더링 됩니다.
store에서 렌더링이 일어나므로 store에서 rAF 동작을 제어해줄 eventhandler 객체를 두고 throttle이나 debounce 등의 이벤트 최척화를 담당했습니다. 

### 고민

이벤트를 처리할 때 최대한 상태로 처리하니 코드는 짧아졌지만, 상태 변경시마다 렌더링이 일어나게 되어있어 매번 화면이 깜빡깜빡거리는 문제가 발생합니다. 

## 미구현 사항

메가드롭과 방향키 이벤트를 구현하지 못했습니다.

2022-03-23 07:46 UTC, namse commented on .idea/jsLibraryMappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea 폴더는 올라오지 않도록 해주세용~

gitignore에 추가하고, git rm --cached 로 지워야 적용될거에요

2022-03-23 07:46 UTC, namse commented on Core/EventHandler.js
> +export class EventHandler{
지원하는 여러 함수가 서로에게 독립적이기 때문에, 이거는 각각 항목에 대해서 클래스를 만들어놓는 편이 좋을 것 같아요. 합칠 필요가 없는게 합쳐져있는 느낌?

2022-03-23 08:52 UTC, namse requested changes
inu, 지난번에도 코드 컨벤션이나 스타일에 대해 피드백해드린 것이 있는데, 이번 PR에서도 개선되지 않은 것 같아요.

이런 코드는 정상적인 코드 리뷰를 할 수 없습니다.

비유를 하자면, 대학교 조교가 과제 체점을 하는데 글씨를 알아볼 수 없게 써져있는걸 0점처리했다는 이야기랑 비슷한 것입니다.

코드는 컴퓨터가 읽고 실행하지만, 컴퓨터 뿐만 아니라 이 코드로 함께 일하는 사람들이 읽고 쓰는 것입니다. 그래서 우리가 가독성이니 뭐니, 인간이 덜 실수하고, 더 잘 일할 수 있게 환경을 열심히 챙기는 것입니다.

idea 폴더가 추가되는걸 보아하니, intellij를 사용하고 계시죠? eslint나 prettier를 적용할 수 있을거에요.
도구의 힘을 빌리시기를 적극적으로 권장드리며, PR에 대해 reject 처리합니다.

수정하신 후 저를 mention 해주시면 다시 리뷰하겠습니다.

2022-03-23 08:52 UTC, namse commented on .gitignore
> +/express-server/yarn.lock
lock은 살려놔주세요. 정확한 이유는 구글링 ㄱㄱ

2022-03-23 08:52 UTC, namse commented on Core/EventHandler.js
> +        }else{ cancelAnimationFrame(this.#currentCallback)}
띄어쓰기가 균일하지 않습니다.

2022-03-23 08:52 UTC, namse commented on Core/View.js
> +        const ok= (eventTarget)=>eventTarget.closest(selector)||children.includes(eventTarget);
무엇에 대한 ok인지 이해할 수 없습니다

2022-03-23 08:52 UTC, namse commented on Core/View.js
> +    throttle(fn,time){this.#handler.throttle(fn,time)}
코드가 너무 다닥다닥 붙어있어 보기가 어렵습니다.

2022-03-23 08:52 UTC, namse commented on Core/View.js
> +    setNext(view){
setNext가 아니라 setLast가 되어야할거같아요. 로직을 보니까 그렇게 되어있네요

2022-03-23 08:52 UTC, namse commented on components/Autocomplete.js
> +// }
불필요한 주석은 지워주세요

2022-03-23 08:52 UTC, namse commented on components/Mainbanner.js
> +
의미없는 공백이 너무 많습니다.

2022-03-23 11:21 UTC, devInu33 commented
> inu, 지난번에도 코드 컨벤션이나 스타일에 대해 피드백해드린 것이 있는데, 이번 PR에서도 개선되지 않은 것 같아요.
> 
> 이런 코드는 정상적인 코드 리뷰를 할 수 없습니다.
> 
> 비유를 하자면, 대학교 조교가 과제 체점을 하는데 글씨를 알아볼 수 없게 써져있는걸 0점처리했다는 이야기랑 비슷한 것입니다.
> 
> 코드는 컴퓨터가 읽고 실행하지만, 컴퓨터 뿐만 아니라 이 코드로 함께 일하는 사람들이 읽고 쓰는 것입니다. 그래서 우리가 가독성이니 뭐니, 인간이 덜 실수하고, 더 잘 일할 수 있게 환경을 열심히 챙기는 것입니다.
> 
> idea 폴더가 추가되는걸 보아하니, intellij를 사용하고 계시죠? eslint나 prettier를 적용할 수 있을거에요. 도구의 힘을 빌리시기를 적극적으로 권장드리며, PR에 대해 reject 처리합니다.
> 
> 수정하신 후 저를 mention 해주시면 다시 리뷰하겠습니다.

@name 수정했습니다!

2022-03-23 11:22 UTC, devInu33 commented
@namse 수정했습니다!

2022-03-23 12:16 UTC, namse commented on util.js
> +export const delay = time=>new Promise(res=>setTimeout(res, time));
여긴 prettier가 안돈거같네요

2022-03-23 12:16 UTC, namse commented on express-server/server.js
> +app.listen(PORT, ()=>console.log(`listening to http://localhost:${PORT}`));
여기도 prettier 돌려주세요. 전체 js 파일 전부 다 돌리시면 됩니다. 명령어 있을거에요

2022-03-23 12:16 UTC, namse commented on components/SearchPopup.js
> +    const newItems = [...recentItems];
이렇게 해버리면 
아래 이벤트 핸들러에서 newItems를 고쳐서 rencetItems에 setState해도,
다른곳에서 recentItems를 건들어버리면 이 newItems에는 영향을 주지 못해서
꼬일 것 같은데 한번 확인해주시겠어요?

2022-03-23 12:16 UTC, namse commented on components/SearchPopup.js
> +    const newItems = [...recentItems];
제 생각엔 이벤트 콜백 안에서 this.state에 접근하셔야할거같은 느낌이 ㅎㅎ

2022-03-23 12:16 UTC, namse commented on components/Mainbanner.js
> +    const auto = () =>
어떤 것을 저장하고 있는 변수인가요? 이름을 좀 더 풍성하게 해서 이해할 수 있게 해봅시다.

2022-03-23 12:16 UTC, namse commented on Core/View.js
> +    this.child ? this.child.setLast(view) : (this.child = view);
이건 의도한게 맞나요? last에다가 view를 추가하는게 맞나요?

2022-03-23 12:16 UTC, namse commented on Core/EventHandler.js
> +  auto = (time, fn, delay) => {
이 auto의 의미는 무엇인가요?

2022-03-23 12:17 UTC, namse commented
잘하셨습니다, 이제 좀 볼 수 있게(?) 되었네요 ㅎㅎ 정말 중요합니다 이누님. 리뷰를 마치도록 하겠습니다.

2022-03-23 12:17 UTC, merged

2022-03-24 04:51 UTC, devInu33 commented
@namse 남세님 죄송한데 제가 PR날린 브랜치가 제 브랜치가 아니라 main에 날렸더라구요 ㅜㅜ 이거 그냥 revert 해도 될까요?

2022-03-24 05:11 UTC, devInu33 commented on Core/EventHandler.js
> +  auto = (time, fn, delay) => {
@namse 몇초 마다 자동으로 실행되는 콜백이라는 의미로 이름을 지어봤습니다!

2022-03-24 05:12 UTC, devInu33 commented on components/SearchPopup.js
> +    const newItems = [...recentItems];
> inu, 지난번에도 코드 컨벤션이나 스타일에 대해 피드백해드린 것이 있는데, 이번 PR에서도 개선되지 않은 것 같아요.
> 
> 이런 코드는 정상적인 코드 리뷰를 할 수 없습니다.
> 
> 비유를 하자면, 대학교 조교가 과제 체점을 하는데 글씨를 알아볼 수 없게 써져있는걸 0점처리했다는 이야기랑 비슷한 것입니다.
> 
> 코드는 컴퓨터가 읽고 실행하지만, 컴퓨터 뿐만 아니라 이 코드로 함께 일하는 사람들이 읽고 쓰는 것입니다. 그래서 우리가 가독성이니 뭐니, 인간이 덜 실수하고, 더 잘 일할 수 있게 환경을 열심히 챙기는 것입니다.
> 
> idea 폴더가 추가되는걸 보아하니, intellij를 사용하고 계시죠? eslint나 prettier를 적용할 수 있을거에요. 도구의 힘을 빌리시기를 적극적으로 권장드리며, PR에 대해 reject 처리합니다.
> 
> 수정하신 후 저를 mention 해주시면 다시 리뷰하겠습니다.

@namse  남세님 어제 코멘트를 못남겨서 남깁니다! ㅜㅜ  쫓기듯이 만들다보니 리뷰해주시는 분 생각을 못하고 코드를 너무 불편하게 올린 것 같습니다 ㅜㅜ 다음부터는 신경쓰도록 하겠습니다. 코멘트 봐주시고 혹시 제가 PR을 main브랜치로 날려서 revert 요청한 상태인데 이건@crong 께서 머지해주시는걸까요?

2022-03-24 05:14 UTC, devInu33 commented
> 잘하셨습니다, 이제 좀 볼 수 있게(?) 되었네요 ㅎㅎ 정말 중요합니다 이누님. 리뷰를 마치도록 하겠습니다.
	
>inu, 지난번에도 코드 컨벤션이나 스타일에 대해 피드백해드린 것이 있는데, 이번 PR에서도 개선되지 않은 것 같아요.
	
	>이런 코드는 정상적인 코드 리뷰를 할 수 없습니다.
	
	>비유를 하자면, 대학교 조교가 과제 체점을 하는데 글씨를 알아볼 수 없게 써져있는걸 0점처리했다는 이야기랑 비슷한 것입니다.
	
	>코드는 컴퓨터가 읽고 실행하지만, 컴퓨터 뿐만 아니라 이 코드로 함께 일하는 사람들이 읽고 쓰는 것입니다. 그래서 우리가 가독성이니 뭐니, 인간이 덜 실수하고, 더 잘 일할 수 있게 환경을 열심히 챙기는 것입니다.
	
	>idea 폴더가 추가되는걸 보아하니, intellij를 사용하고 계시죠? eslint나 prettier를 적용할 수 있을거에요. 도구의 힘을 빌리시기를 적극적으로 권장드리며, PR에 대해 reject 처리합니다.
	
>	수정하신 후 저를 mention 해주시면 다시 리뷰하겠습니다.

@namse 남세님 어제 코멘트를 못남겨서 남깁니다! ㅜㅜ 쫓기듯이 만들다보니 리뷰해주시는 분 생각을 못하고 코드를 너무 불편하게 올린 것 같습니다 ㅜㅜ 다음부터는 신경쓰도록 하겠습니다. 코멘트 봐주시고 혹시 제가 PR을 main브랜치로 날려서 revert 요청한 상태인데 이건@Crong 께서 머지해주시는걸까요?

2022-03-24 05:16 UTC, devInu33 commented on Core/View.js
> +    this.child ? this.child.setLast(view) : (this.child = view);
@의도는 자식이 있을 경우 자식끼리 서로 형재노드로 연결해주시는 것이었는데 포인터를 start와 end로 두고 추가하는게 낫지 않나 생각중입니다!

2022-03-24 05:23 UTC, devInu33 commented on components/SearchPopup.js
> +    const newItems = [...recentItems];
@namse 이부분 맞는 것 같습니다! 그런데 이벤트 콜백 내부에서 매번 getState해야하는 부분은 뭔가 고쳐봐야 할 것 같습니다.
그런데 고민이 있습니다. rAF에 관한 고민인데 현재 저는 각 뷰들의 setState을 store에서 한 번에 모아서 프레임마다 debounce해줄 수 있도록 store에 이벤트 핸들러를 등록하고 setState 요청이 왔을 경우 render를 전부 디바운스 시켰습니다!
 그런데 각 뷰들도 각각 자동 슬라이더 이벤트라던가 쓰로틀링이 필요한게 있어서 각 뷰들도 이벤트핸들러를 상속받아서 사용할 수 있게 해놨어요! 결론은 setState하는 requestAnimationFrame과, 각 뷰에서 쓰로틀링, 디바운스, 자동이벤트 시에 사용하는 requestAnimationFrame이 제각각인데(같은 객체의 서로 다른 인스턴스) 저는 지금 `this.startAuto(()=>this.setState())` 이런식으로 쓰고 있거든요! 이러면 하나의 rAF 안에 다른 rAF를 밀어넣는 건데 문제가 없을까요?

2022-03-24 07:51 UTC, namse commented on components/SearchPopup.js
> +    const newItems = [...recentItems];
그래도 상관 없을거라 생각합니다. setTimeout이랑 별 반 다르지 않다는걸 생각해보면 그냥 뭐 콜백 등록해놓고 나중에 콜해주는 정도일거니깐요.

콜백 내부에서 매번 getState하는건 상관 없다고 봐요. 성능 차이도 없고 논리적으로 그게 맞으니깐요 ㅎㅎ

2022-03-24 07:52 UTC, namse commented on Core/View.js
> +    this.child ? this.child.setLast(view) : (this.child = view);
아.............
그러면 Inu, 이거 이렇게 합시다.
이누는 지금 this.child가 linked list라고 생각하고 있는데, 이름이 child라는 단수 이기 때문에 사람들이 그렇게 느끼지 못할거에요.

단순하게, this.children 이란 배열을 만들고 그걸로 자식들을 관리하는 편이 더 좋을거같아요.

2022-03-24 07:53 UTC, namse commented on Core/EventHandler.js
> +  auto = (time, fn, delay) => {
아마 저처럼 대부분의 사람들이 auto라는 이름만으로는 그 의도를 모를 것 같아요. 이름을 좀 더 풍성하게 지어봅시다.

2022-03-24 07:55 UTC, namse commented
크롱께서 머지해주신 것 같고,
근데 Inu, 이게 단순히 `리뷰하는 사람을 위해서 이렇게 짜면 안된다~` 가 아니라는 것은 알고 계셔야해요.
1) 나중에 Inu와 함께 일하는 동료를 위해, 그리고 2) 나중에 이 코드를 보고 유지보수해야하는 자기 자신을 위해 이렇게 짜면 안되는거에요.

그래서 예전에 제가 그런 말을 한 적이 있을거에요, 혼자 하는 작은 프로젝트면 신경 안써도 된다고요 ㅎㅎ

Inu도 일 잘하는, 협력 잘하는 사람이랑 같이 일하고 싶죠? Inu 또한 이번 PR처럼 좀 더 신경쓰면 그렇게 될 수 있을거라 생각해요. 화이팅입니다.